network_params:
  seq_len: 512
  batch_size: 1
  head_num: 12
  kv_head_num: 12
  head_dim: 64
  token_dim: 768
  ffn_hidden_dim: 3072
  layer_num: 1
system_params:
  dpu_num: 1
  nr_tasklets: 16
  qkv_lut_pim_binary: ./build/bin/dpu_bin_qkv
  o_lut_pim_binary: ./build/bin/dpu_bin_o
  ffn1_lut_pim_binary: ./build/bin/dpu_bin_ffn1
  ffn2_lut_pim_binary: ./build/bin/dpu_bin_ffn2
  num_threads: 1
kernel_params:
  qkv_scale: 0.1
  qkv_bias: 0.2
  qkv_num_codebook: 512
  qkv_num_centroid: 16
  qkv_input_parallelism: 1
  qkv_lut_parallelism: 1
  qkv_loop_order: 0
  qkv_lut_load_type: 2
  qkv_n_mtile_size: 64
  qkv_feature_mtile_size: 32
  qkv_cb_mtile_size: 128
  qkv_feature_load_tile_size: 8
  qkv_cb_load_tile_size: 128
  o_scale: 0.1
  o_bias: 0.2
  o_num_codebook: 512
  o_num_centroid: 16
  o_input_parallelism: 1
  o_lut_parallelism: 1
  o_loop_order: 0
  o_lut_load_type: 2
  o_n_mtile_size: 64
  o_feature_mtile_size: 32
  o_cb_mtile_size: 128
  o_feature_load_tile_size: 8
  o_cb_load_tile_size: 128
  ffn1_scale: 0.1
  ffn1_bias: 0.2
  ffn1_num_codebook: 512
  ffn1_num_centroid: 16
  ffn1_input_parallelism: 1
  ffn1_lut_parallelism: 1
  ffn1_loop_order: 0
  ffn1_lut_load_type: 2
  ffn1_n_mtile_size: 64
  ffn1_feature_mtile_size: 32
  ffn1_cb_mtile_size: 128
  ffn1_feature_load_tile_size: 8
  ffn1_cb_load_tile_size: 128
  ffn2_scale: 0.1
  ffn2_bias: 0.2
  ffn2_num_codebook: 2048
  ffn2_num_centroid: 16
  ffn2_input_parallelism: 1
  ffn2_lut_parallelism: 1
  ffn2_loop_order: 0
  ffn2_lut_load_type: 2
  ffn2_n_mtile_size: 64
  ffn2_feature_mtile_size: 32
  ffn2_cb_mtile_size: 128
  ffn2_feature_load_tile_size: 8
  ffn2_cb_load_tile_size: 128
